### ISSUE TITLE
Additional Ride with GPS login Options

### ISSUE THREAD

**Issue by JHa13y** [gazer22/brevet.app#3]
I don't know if this is doable using the RWGP API you are using, but RWGPS uses additional authorizations for login such as facebook.  By only using the email/password option, it was difficult to track down what those actually were as I signed up and login using facebook authentication.

**Comment by gazer22** [comment]
Interesting.  RWGPS API is far less slick than strava's.  Unfortunately, the API appears to rely solely on email/password.  (Docs indicate that and a quick check of a more established app, Epic Ride Weather, shows the same thing).

On the plus side, you should only have to do it once.

**Comment by gazer22** [comment]
@JHa13y  How were you able to resolve?

RWGPS site gives passing reference to registering via f-book:
https://ridewithgps.com/help/forgot-your-password

**Comment by gazer22** [comment]
Added some language that it's clunky if you use Facebook to log in to ride with GPS.  Not sure there's a better way.
